/*
** DON'T EDIT THIS FILE **
It's generated by Zapatos, and is liable to be overwritten

Generated using version 0.1.36 on 2020-05-28T16:01:47.803Z

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 George MacKerron
Released under the MIT licence: see LICENCE file
*/
