/*
** DON'T EDIT THIS FILE **
It's generated by Zapatos, and is liable to be overwritten

Generated using version 0.1.33 on 2020-05-27T13:50:42.713Z

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 George MacKerron
Released under the MIT licence: see LICENCE file
*/
