/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v3.3.0), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';
  import type * as c from 'zapatos/custom';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 101 }

  type JSONSelectableFromSelectable<T> = { [K in keyof T]:
    Date extends T[K] ? Exclude<T[K], Date> | db.DateString :
    Date[] extends T[K] ? Exclude<T[K], Date[]> | db.DateString[] :
    T[K]
  };

  /* === schema: public === */

  /* --- enums --- */

  export type appleEnvironment = 'PROD' | 'Sandbox';
  export namespace every {
    export type appleEnvironment = ['PROD', 'Sandbox'];
  }

  /* --- tables --- */

  export namespace appleTransactions {
    export type Table = 'appleTransactions';
    export interface Selectable {
      /**
      * **appleTransactions.environment**
      * - `appleEnvironment` in database
      * - `NOT NULL`, no default
      */
      environment: appleEnvironment;
      /**
      * **appleTransactions.originalTransactionId**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      originalTransactionId: string;
      /**
      * **appleTransactions.accountId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      accountId: number;
      /**
      * **appleTransactions.latestReceiptData**
      * - `text` in database
      * - Nullable, no default
      */
      latestReceiptData: string | null;
    }
    export interface Whereable {
      /**
      * **appleTransactions.environment**
      * - `appleEnvironment` in database
      * - `NOT NULL`, no default
      */
      environment?: appleEnvironment | db.Parameter<appleEnvironment> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, appleEnvironment | db.Parameter<appleEnvironment> | db.SQLFragment | db.ParentColumn>;
      /**
      * **appleTransactions.originalTransactionId**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      originalTransactionId?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **appleTransactions.accountId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      accountId?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **appleTransactions.latestReceiptData**
      * - `text` in database
      * - Nullable, no default
      */
      latestReceiptData?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **appleTransactions.environment**
      * - `appleEnvironment` in database
      * - `NOT NULL`, no default
      */
      environment: appleEnvironment | db.Parameter<appleEnvironment> | db.SQLFragment;
      /**
      * **appleTransactions.originalTransactionId**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      originalTransactionId: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **appleTransactions.accountId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      accountId: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **appleTransactions.latestReceiptData**
      * - `text` in database
      * - Nullable, no default
      */
      latestReceiptData?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **appleTransactions.environment**
      * - `appleEnvironment` in database
      * - `NOT NULL`, no default
      */
      environment?: appleEnvironment | db.Parameter<appleEnvironment> | db.SQLFragment | db.SQLFragment<any, appleEnvironment | db.Parameter<appleEnvironment> | db.SQLFragment>;
      /**
      * **appleTransactions.originalTransactionId**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      originalTransactionId?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **appleTransactions.accountId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      accountId?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **appleTransactions.latestReceiptData**
      * - `text` in database
      * - Nullable, no default
      */
      latestReceiptData?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'appleTransactionsPrimaryKey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace arrays {
    export type Table = 'arrays';
    export interface Selectable {
      /**
      * **arrays.jsonValue**
      * - `jsonb` in database
      * - Nullable, no default
      */
      jsonValue: db.JSONValue | null;
      /**
      * **arrays.textArray**
      * - `_text` in database
      * - Nullable, no default
      */
      textArray: string[] | null;
    }
    export interface Whereable {
      /**
      * **arrays.jsonValue**
      * - `jsonb` in database
      * - Nullable, no default
      */
      jsonValue?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **arrays.textArray**
      * - `_text` in database
      * - Nullable, no default
      */
      textArray?: string[] | db.Parameter<string[]> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string[] | db.Parameter<string[]> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **arrays.jsonValue**
      * - `jsonb` in database
      * - Nullable, no default
      */
      jsonValue?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment;
      /**
      * **arrays.textArray**
      * - `_text` in database
      * - Nullable, no default
      */
      textArray?: string[] | db.Parameter<string[]> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **arrays.jsonValue**
      * - `jsonb` in database
      * - Nullable, no default
      */
      jsonValue?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **arrays.textArray**
      * - `_text` in database
      * - Nullable, no default
      */
      textArray?: string[] | db.Parameter<string[]> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string[] | db.Parameter<string[]> | null | db.DefaultType | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = never;
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace authors {
    export type Table = 'authors';
    export interface Selectable {
      /**
      * **authors.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('authors_id_seq'::regclass)`
      */
      id: number;
      /**
      * **authors.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **authors.isLiving**
      * - `bool` in database
      * - Nullable, no default
      */
      isLiving: boolean | null;
    }
    export interface Whereable {
      /**
      * **authors.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('authors_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **authors.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **authors.isLiving**
      * - `bool` in database
      * - Nullable, no default
      */
      isLiving?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **authors.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('authors_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **authors.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **authors.isLiving**
      * - `bool` in database
      * - Nullable, no default
      */
      isLiving?: boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **authors.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('authors_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **authors.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **authors.isLiving**
      * - `bool` in database
      * - Nullable, no default
      */
      isLiving?: boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'authors_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace bankAccounts {
    export type Table = 'bankAccounts';
    export interface Selectable {
      /**
      * **bankAccounts.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('"bankAccounts_id_seq"'::regclass)`
      */
      id: number;
      /**
      * **bankAccounts.balance**
      * - `int4` in database
      * - `NOT NULL`, default: `0`
      */
      balance: number;
    }
    export interface Whereable {
      /**
      * **bankAccounts.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('"bankAccounts_id_seq"'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **bankAccounts.balance**
      * - `int4` in database
      * - `NOT NULL`, default: `0`
      */
      balance?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **bankAccounts.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('"bankAccounts_id_seq"'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **bankAccounts.balance**
      * - `int4` in database
      * - `NOT NULL`, default: `0`
      */
      balance?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **bankAccounts.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('"bankAccounts_id_seq"'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **bankAccounts.balance**
      * - `int4` in database
      * - `NOT NULL`, default: `0`
      */
      balance?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'bankAccounts_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace books {
    export type Table = 'books';
    export interface Selectable {
      /**
      * **books.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('books_id_seq'::regclass)`
      */
      id: number;
      /**
      * **books.authorId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      authorId: number;
      /**
      * **books.title**
      * - `text` in database
      * - Nullable, no default
      */
      title: string | null;
      /**
      * **books.createdAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      createdAt: Date;
    }
    export interface Whereable {
      /**
      * **books.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('books_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **books.authorId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      authorId?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **books.title**
      * - `text` in database
      * - Nullable, no default
      */
      title?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **books.createdAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      createdAt?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **books.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('books_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **books.authorId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      authorId: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **books.title**
      * - `text` in database
      * - Nullable, no default
      */
      title?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **books.createdAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      createdAt?: Date | db.Parameter<Date> | db.DateString | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **books.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('books_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **books.authorId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      authorId?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **books.title**
      * - `text` in database
      * - Nullable, no default
      */
      title?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **books.createdAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      createdAt?: Date | db.Parameter<Date> | db.DateString | db.DefaultType | db.SQLFragment | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.DefaultType | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'books_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace doctors {
    export type Table = 'doctors';
    export interface Selectable {
      /**
      * **doctors.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('doctors_id_seq'::regclass)`
      */
      id: number;
      /**
      * **doctors.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string;
    }
    export interface Whereable {
      /**
      * **doctors.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('doctors_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **doctors.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **doctors.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('doctors_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **doctors.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **doctors.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('doctors_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **doctors.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'doctors_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace emailAuthentication {
    export type Table = 'emailAuthentication';
    export interface Selectable {
      /**
      * **emailAuthentication.email**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      email: string;
      /**
      * **emailAuthentication.consecutiveFailedLogins**
      * - `int4` in database
      * - `NOT NULL`, default: `0`
      */
      consecutiveFailedLogins: number;
      /**
      * **emailAuthentication.lastFailedLogin**
      * - `timestamptz` in database
      * - Nullable, no default
      */
      lastFailedLogin: Date | null;
    }
    export interface Whereable {
      /**
      * **emailAuthentication.email**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **emailAuthentication.consecutiveFailedLogins**
      * - `int4` in database
      * - `NOT NULL`, default: `0`
      */
      consecutiveFailedLogins?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **emailAuthentication.lastFailedLogin**
      * - `timestamptz` in database
      * - Nullable, no default
      */
      lastFailedLogin?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **emailAuthentication.email**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      email: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **emailAuthentication.consecutiveFailedLogins**
      * - `int4` in database
      * - `NOT NULL`, default: `0`
      */
      consecutiveFailedLogins?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **emailAuthentication.lastFailedLogin**
      * - `timestamptz` in database
      * - Nullable, no default
      */
      lastFailedLogin?: Date | db.Parameter<Date> | db.DateString | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **emailAuthentication.email**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **emailAuthentication.consecutiveFailedLogins**
      * - `int4` in database
      * - `NOT NULL`, default: `0`
      */
      consecutiveFailedLogins?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **emailAuthentication.lastFailedLogin**
      * - `timestamptz` in database
      * - Nullable, no default
      */
      lastFailedLogin?: Date | db.Parameter<Date> | db.DateString | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | null | db.DefaultType | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'emailAuthentication_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace employees {
    export type Table = 'employees';
    export interface Selectable {
      /**
      * **employees.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('employees_id_seq'::regclass)`
      */
      id: number;
      /**
      * **employees.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **employees.managerId**
      * - `int4` in database
      * - Nullable, no default
      */
      managerId: number | null;
    }
    export interface Whereable {
      /**
      * **employees.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('employees_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **employees.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **employees.managerId**
      * - `int4` in database
      * - Nullable, no default
      */
      managerId?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **employees.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('employees_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **employees.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **employees.managerId**
      * - `int4` in database
      * - Nullable, no default
      */
      managerId?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **employees.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('employees_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **employees.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **employees.managerId**
      * - `int4` in database
      * - Nullable, no default
      */
      managerId?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'employees_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace nameCounts {
    export type Table = 'nameCounts';
    export interface Selectable {
      /**
      * **nameCounts.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **nameCounts.count**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      count: number;
    }
    export interface Whereable {
      /**
      * **nameCounts.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **nameCounts.count**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      count?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **nameCounts.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **nameCounts.count**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      count: number | db.Parameter<number> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **nameCounts.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **nameCounts.count**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      count?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'nameCounts_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace photos {
    export type Table = 'photos';
    export interface Selectable {
      /**
      * **photos.photoId**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      photoId: number;
      /**
      * **photos.url**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      url: string;
    }
    export interface Whereable {
      /**
      * **photos.photoId**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      photoId?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **photos.url**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      url?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **photos.photoId**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      photoId?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **photos.url**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      url: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **photos.photoId**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      photoId?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **photos.url**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      url?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'photos_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace shifts {
    export type Table = 'shifts';
    export interface Selectable {
      /**
      * **shifts.day**
      * - `date` in database
      * - `NOT NULL`, no default
      */
      day: Date;
      /**
      * **shifts.doctorId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      doctorId: number;
    }
    export interface Whereable {
      /**
      * **shifts.day**
      * - `date` in database
      * - `NOT NULL`, no default
      */
      day?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn>;
      /**
      * **shifts.doctorId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      doctorId?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **shifts.day**
      * - `date` in database
      * - `NOT NULL`, no default
      */
      day: Date | db.Parameter<Date> | db.DateString | db.SQLFragment;
      /**
      * **shifts.doctorId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      doctorId: number | db.Parameter<number> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **shifts.day**
      * - `date` in database
      * - `NOT NULL`, no default
      */
      day?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment>;
      /**
      * **shifts.doctorId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      doctorId?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'shifts_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace stores {
    export type Table = 'stores';
    export interface Selectable {
      /**
      * **stores.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('stores_id_seq'::regclass)`
      */
      id: number;
      /**
      * **stores.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **stores.geom**
      * - `geometry` in database
      * - `NOT NULL`, no default
      */
      geom: c.PgGeometry;
    }
    export interface Whereable {
      /**
      * **stores.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('stores_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **stores.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **stores.geom**
      * - `geometry` in database
      * - `NOT NULL`, no default
      */
      geom?: c.PgGeometry | db.Parameter<c.PgGeometry> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, c.PgGeometry | db.Parameter<c.PgGeometry> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **stores.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('stores_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **stores.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **stores.geom**
      * - `geometry` in database
      * - `NOT NULL`, no default
      */
      geom: c.PgGeometry | db.Parameter<c.PgGeometry> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **stores.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('stores_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **stores.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **stores.geom**
      * - `geometry` in database
      * - `NOT NULL`, no default
      */
      geom?: c.PgGeometry | db.Parameter<c.PgGeometry> | db.SQLFragment | db.SQLFragment<any, c.PgGeometry | db.Parameter<c.PgGeometry> | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'stores_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace subjectPhotos {
    export type Table = 'subjectPhotos';
    export interface Selectable {
      /**
      * **subjectPhotos.subjectId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      subjectId: number;
      /**
      * **subjectPhotos.photoId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      photoId: number;
    }
    export interface Whereable {
      /**
      * **subjectPhotos.subjectId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      subjectId?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **subjectPhotos.photoId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      photoId?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **subjectPhotos.subjectId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      subjectId: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **subjectPhotos.photoId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      photoId: number | db.Parameter<number> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **subjectPhotos.subjectId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      subjectId?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **subjectPhotos.photoId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      photoId?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'userphotosunique';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace subjects {
    export type Table = 'subjects';
    export interface Selectable {
      /**
      * **subjects.subjectId**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      subjectId: number;
      /**
      * **subjects.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string;
    }
    export interface Whereable {
      /**
      * **subjects.subjectId**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      subjectId?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **subjects.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **subjects.subjectId**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      subjectId?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **subjects.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **subjects.subjectId**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      subjectId?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **subjects.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'subjects_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace tags {
    export type Table = 'tags';
    export interface Selectable {
      /**
      * **tags.tag**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      tag: string;
      /**
      * **tags.bookId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      bookId: number;
    }
    export interface Whereable {
      /**
      * **tags.tag**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      tag?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **tags.bookId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      bookId?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **tags.tag**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      tag: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **tags.bookId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      bookId: number | db.Parameter<number> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **tags.tag**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      tag?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **tags.bookId**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      bookId?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'tagsUniqueIdx';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace usedVoucherCodes {
    export type Table = 'usedVoucherCodes';
    export interface Selectable {
      /**
      * **usedVoucherCodes.code**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      code: string;
      /**
      * **usedVoucherCodes.redeemedAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      redeemedAt: Date;
    }
    export interface Whereable {
      /**
      * **usedVoucherCodes.code**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      code?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **usedVoucherCodes.redeemedAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      redeemedAt?: Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **usedVoucherCodes.code**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      code: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **usedVoucherCodes.redeemedAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      redeemedAt?: Date | db.Parameter<Date> | db.DateString | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **usedVoucherCodes.code**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      code?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **usedVoucherCodes.redeemedAt**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      redeemedAt?: Date | db.Parameter<Date> | db.DateString | db.DefaultType | db.SQLFragment | db.SQLFragment<any, Date | db.Parameter<Date> | db.DateString | db.DefaultType | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'usedVoucherCodes_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace users {
    export type Table = 'users';
    export interface Selectable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      id: number;
      /**
      * **users.ipOctet**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      ipOctet: number;
      /**
      * **users.friendlyName**
      * - `text` in database
      * - Nullable, no default
      */
      friendlyName: string | null;
    }
    export interface Whereable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.ipOctet**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      ipOctet?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.friendlyName**
      * - `text` in database
      * - Nullable, no default
      */
      friendlyName?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **users.ipOctet**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      ipOctet?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **users.friendlyName**
      * - `text` in database
      * - Nullable, no default
      */
      friendlyName?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.ipOctet**
      * - `int4` in database
      * - `NOT NULL`, identity column
      */
      ipOctet?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.friendlyName**
      * - `text` in database
      * - Nullable, no default
      */
      friendlyName?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
    }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'users_pkey' | 'users_ipOctet_key';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* === cross-table types === */

  export type Table = appleTransactions.Table | arrays.Table | authors.Table | bankAccounts.Table | books.Table | doctors.Table | emailAuthentication.Table | employees.Table | nameCounts.Table | photos.Table | shifts.Table | stores.Table | subjectPhotos.Table | subjects.Table | tags.Table | usedVoucherCodes.Table | users.Table;
  export type Selectable = appleTransactions.Selectable | arrays.Selectable | authors.Selectable | bankAccounts.Selectable | books.Selectable | doctors.Selectable | emailAuthentication.Selectable | employees.Selectable | nameCounts.Selectable | photos.Selectable | shifts.Selectable | stores.Selectable | subjectPhotos.Selectable | subjects.Selectable | tags.Selectable | usedVoucherCodes.Selectable | users.Selectable;
  export type Whereable = appleTransactions.Whereable | arrays.Whereable | authors.Whereable | bankAccounts.Whereable | books.Whereable | doctors.Whereable | emailAuthentication.Whereable | employees.Whereable | nameCounts.Whereable | photos.Whereable | shifts.Whereable | stores.Whereable | subjectPhotos.Whereable | subjects.Whereable | tags.Whereable | usedVoucherCodes.Whereable | users.Whereable;
  export type Insertable = appleTransactions.Insertable | arrays.Insertable | authors.Insertable | bankAccounts.Insertable | books.Insertable | doctors.Insertable | emailAuthentication.Insertable | employees.Insertable | nameCounts.Insertable | photos.Insertable | shifts.Insertable | stores.Insertable | subjectPhotos.Insertable | subjects.Insertable | tags.Insertable | usedVoucherCodes.Insertable | users.Insertable;
  export type Updatable = appleTransactions.Updatable | arrays.Updatable | authors.Updatable | bankAccounts.Updatable | books.Updatable | doctors.Updatable | emailAuthentication.Updatable | employees.Updatable | nameCounts.Updatable | photos.Updatable | shifts.Updatable | stores.Updatable | subjectPhotos.Updatable | subjects.Updatable | tags.Updatable | usedVoucherCodes.Updatable | users.Updatable;
  export type UniqueIndex = appleTransactions.UniqueIndex | arrays.UniqueIndex | authors.UniqueIndex | bankAccounts.UniqueIndex | books.UniqueIndex | doctors.UniqueIndex | emailAuthentication.UniqueIndex | employees.UniqueIndex | nameCounts.UniqueIndex | photos.UniqueIndex | shifts.UniqueIndex | stores.UniqueIndex | subjectPhotos.UniqueIndex | subjects.UniqueIndex | tags.UniqueIndex | usedVoucherCodes.UniqueIndex | users.UniqueIndex;
  export type Column = appleTransactions.Column | arrays.Column | authors.Column | bankAccounts.Column | books.Column | doctors.Column | emailAuthentication.Column | employees.Column | nameCounts.Column | photos.Column | shifts.Column | stores.Column | subjectPhotos.Column | subjects.Column | tags.Column | usedVoucherCodes.Column | users.Column;
  export type AllTables = [appleTransactions.Table, arrays.Table, authors.Table, bankAccounts.Table, books.Table, doctors.Table, emailAuthentication.Table, employees.Table, nameCounts.Table, photos.Table, shifts.Table, stores.Table, subjectPhotos.Table, subjects.Table, tags.Table, usedVoucherCodes.Table, users.Table];
  export type AllMaterializedViews = [];


  export type SelectableForTable<T extends Table> = {
    appleTransactions: appleTransactions.Selectable;
    arrays: arrays.Selectable;
    authors: authors.Selectable;
    bankAccounts: bankAccounts.Selectable;
    books: books.Selectable;
    doctors: doctors.Selectable;
    emailAuthentication: emailAuthentication.Selectable;
    employees: employees.Selectable;
    nameCounts: nameCounts.Selectable;
    photos: photos.Selectable;
    shifts: shifts.Selectable;
    stores: stores.Selectable;
    subjectPhotos: subjectPhotos.Selectable;
    subjects: subjects.Selectable;
    tags: tags.Selectable;
    usedVoucherCodes: usedVoucherCodes.Selectable;
    users: users.Selectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    appleTransactions: appleTransactions.Whereable;
    arrays: arrays.Whereable;
    authors: authors.Whereable;
    bankAccounts: bankAccounts.Whereable;
    books: books.Whereable;
    doctors: doctors.Whereable;
    emailAuthentication: emailAuthentication.Whereable;
    employees: employees.Whereable;
    nameCounts: nameCounts.Whereable;
    photos: photos.Whereable;
    shifts: shifts.Whereable;
    stores: stores.Whereable;
    subjectPhotos: subjectPhotos.Whereable;
    subjects: subjects.Whereable;
    tags: tags.Whereable;
    usedVoucherCodes: usedVoucherCodes.Whereable;
    users: users.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    appleTransactions: appleTransactions.Insertable;
    arrays: arrays.Insertable;
    authors: authors.Insertable;
    bankAccounts: bankAccounts.Insertable;
    books: books.Insertable;
    doctors: doctors.Insertable;
    emailAuthentication: emailAuthentication.Insertable;
    employees: employees.Insertable;
    nameCounts: nameCounts.Insertable;
    photos: photos.Insertable;
    shifts: shifts.Insertable;
    stores: stores.Insertable;
    subjectPhotos: subjectPhotos.Insertable;
    subjects: subjects.Insertable;
    tags: tags.Insertable;
    usedVoucherCodes: usedVoucherCodes.Insertable;
    users: users.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    appleTransactions: appleTransactions.Updatable;
    arrays: arrays.Updatable;
    authors: authors.Updatable;
    bankAccounts: bankAccounts.Updatable;
    books: books.Updatable;
    doctors: doctors.Updatable;
    emailAuthentication: emailAuthentication.Updatable;
    employees: employees.Updatable;
    nameCounts: nameCounts.Updatable;
    photos: photos.Updatable;
    shifts: shifts.Updatable;
    stores: stores.Updatable;
    subjectPhotos: subjectPhotos.Updatable;
    subjects: subjects.Updatable;
    tags: tags.Updatable;
    usedVoucherCodes: usedVoucherCodes.Updatable;
    users: users.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    appleTransactions: appleTransactions.UniqueIndex;
    arrays: arrays.UniqueIndex;
    authors: authors.UniqueIndex;
    bankAccounts: bankAccounts.UniqueIndex;
    books: books.UniqueIndex;
    doctors: doctors.UniqueIndex;
    emailAuthentication: emailAuthentication.UniqueIndex;
    employees: employees.UniqueIndex;
    nameCounts: nameCounts.UniqueIndex;
    photos: photos.UniqueIndex;
    shifts: shifts.UniqueIndex;
    stores: stores.UniqueIndex;
    subjectPhotos: subjectPhotos.UniqueIndex;
    subjects: subjects.UniqueIndex;
    tags: tags.UniqueIndex;
    usedVoucherCodes: usedVoucherCodes.UniqueIndex;
    users: users.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    appleTransactions: appleTransactions.Column;
    arrays: arrays.Column;
    authors: authors.Column;
    bankAccounts: bankAccounts.Column;
    books: books.Column;
    doctors: doctors.Column;
    emailAuthentication: emailAuthentication.Column;
    employees: employees.Column;
    nameCounts: nameCounts.Column;
    photos: photos.Column;
    shifts: shifts.Column;
    stores: stores.Column;
    subjectPhotos: subjectPhotos.Column;
    subjects: subjects.Column;
    tags: tags.Column;
    usedVoucherCodes: usedVoucherCodes.Column;
    users: users.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    appleTransactions: appleTransactions.SQL;
    arrays: arrays.SQL;
    authors: authors.SQL;
    bankAccounts: bankAccounts.SQL;
    books: books.SQL;
    doctors: doctors.SQL;
    emailAuthentication: emailAuthentication.SQL;
    employees: employees.SQL;
    nameCounts: nameCounts.SQL;
    photos: photos.SQL;
    shifts: shifts.SQL;
    stores: stores.SQL;
    subjectPhotos: subjectPhotos.SQL;
    subjects: subjects.SQL;
    tags: tags.SQL;
    usedVoucherCodes: usedVoucherCodes.SQL;
    users: users.SQL;
  }[T];

}
